name: Build & Deploy Angular App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Build Docker Image
        run: docker build -t ngrx-counter-demo .

      # Optional: Push to DockerHub (needed if deploy runner isn’t the same machine)
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Push Docker Image
      #   run: |
      #     docker tag ngrx-counter-demo yourusername/ngrx-counter-demo:latest
      #     docker push yourusername/ngrx-counter-demo:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Free Port 8080
        run: |
          if lsof -i:8080 -t >/dev/null; then
            echo "Port 8080 in use, killing process..."
            kill -9 $(lsof -i:8080 -t)
          else
            echo "Port 8080 is free."
          fi

      - name: Restart Docker Container
        run: |
          docker stop ngrx-counter || true
          docker rm ngrx-counter || true
          docker run -d -p 8080:80 --name ngrx-counter ngrx-counter-demo
